services:
  fastapi:
    build: ./ai_fastapi_agent
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-service-account-key.json
    volumes:
      - ./firebase-service-account-key.json:/app/firebase-service-account-key.json:ro

  threejs:
    build: ./twin3d
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
      - threejs 